port = 'PORT'
proxy = 'IS_PROXIED'
num_workers = 'NUM_WORKERS'
log_level = 'LOG_LEVEL'
log_output = 'LOG_OUTPUT'
service_url = 'SERVICE_URL'
default_avatar = 'DEFAULT_AVATAR'
redis_url = 'REDIS_URL'
rpc_node = 'RPC_NODE'
[upload_store]
type = 'UPLOAD_STORAGE_TYPE'
s3_bucket = 'UPLOAD_S3_BUCKET'
[proxy_store]
type = 'PROXY_STORAGE_TYPE'
s3_bucket = 'PROXY_S3_BUCKET'
max_image_width = 'PROXY_MAX_IMAGE_WIDTH'
max_image_height = 'PROXY_MAX_IMAGE_HEIGHT'
max_custom_image_width = 'PROXY_MAX_CUSTOM_IMAGE_WIDTH'
max_custom_image_height = 'PROXY_MAX_CUSTOM_IMAGE_HEIGHT'
